---
# tasks file for satellite_reg
- name: Ensure chronyd is enabled and started
  service:
    name: chronyd
    enabled: True
    state: started

- name: Ensure rhsmcertd is enabled and started
  service:
    name: rhsmcertd
    enabled: True
    state: started

#- name: Check if consumer RPM is installed
#  command: "rpm -qa"
#  register: katello_check

#- name: Ensure consumer RPM is installed
#  command: 'rpm -Uvh http://"{{ satellite_reg_servername }}"/pub/katello-ca-consumer-latest.noarch.rpm'
#  when: "'katello-ca-consumer' not in katello_check.stdout"

- name: Remove all subscriptions
  command: subscription-manager remove --all
  ignore_errors: true

- name: Unregister from subscription management
  command: subscription-manager unregister
  ignore_errors: true

- name: Clean out configuration data
  command: subscription-manager clean

- name: Print registration information
  debug:
    msg: "Registering {{ satellite_reg_consumer_name | default(inventory_hostname, true) }} with Activation Key {{ satellite_reg_activation_key }} and Organization {{ satellite_reg_organization }} to {{ satellite_reg_servername }} with server_insecure set to {{ satellite_reg_server_insecure }}"

- name: Ensure system is subscribed
  community.general.redhat_subscription:
    activationkey: "{{ satellite_reg_activation_key }}"
    consumer_name: "{{ satellite_reg_consumer_name | default(inventory_hostname, true) }}"
    org_id: "{{ satellite_reg_organization }}"
    server_hostname: "{{ satellite_reg_servername }}"
    server_insecure: "{{ satellite_reg_server_insecure }}"
    state: present

#- name: Ensure katello-agent is installed
#  package:
#    name: katello-agent
#    state: present

#- name: Ensure goferd is enabled and started
#  service:
#    name: goferd
#    enabled: True
#    state: started
